name: Generate Snake

# Run every 6 hours and allow manual trigger
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Generate the snake graph
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AbhinekDangi03 # Replace with your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show build status for debugging
      - run: git status

      # Push generated files to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output # Ensure this is your desired branch
          force: true

      # Publish the snake to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
